sudo: required
services:
  - docker

before_install:
  - docker build -t anmol2srivastava/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true anmol2srivastava/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-992382424575"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY" 
